### ISSUE TITLE
2.1.1.giga24 Gigahorse 2.0 Node / Farmer powershell says virus

### ISSUE THREAD

**Issue by Allvasound** [madMAx43v3r/chia-gigahorse#240]
I have the following problem.
Powershell tells me that when I open Gigahorse in the terminal and enter the command: .\chia start farmer, the message appears saying the file cannot be opened because it may contain a virus. I have no problems with the previous version giga23
I am thankful for every help.

Best regards

**Comment by spleen911** [comment]
Same here (from chia log below). I added an exclusion. So far my XCH hasn't disappeared [sarcasm]

`OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software
`

<img width="604" alt="image" src="https://github.com/madMAx43v3r/chia-gigahorse/assets/68015090/ce6d6c72-f14e-479b-a507-36a27b05b158">

**Comment by Kruger1981** [comment]
Right click on the file, go to properties and unblock the file. After that try again

**Comment by Allvasound** [comment]
Work, thank you

**Comment by spleen911** [comment]
Note if you can launch [after unblock], but after a few hours, you get WinError 225 ... add a Windows Defender exclusion for the folder or chia.exe process. I always unblock after download and ran for almost 8 hours before getting the errors. After adding the exclusion, everything returned to normal and I didn't even have to restart the daemon/farmer/etc.

My node/farmer is on Windows Server 2022 (21H2).
