### ISSUE TITLE
Chia farm not send partials.

### ISSUE THREAD

**Issue by LimakKAAM** [madMAx43v3r/chia-gigahorse#253]
I have big problem,  my chia farm 6600 plots, chia farm not send partials.  Gigahorse version 2.1.1 mining on space pool 

About 4 days already.  What is the solution?

Very high missing signature point!

This is very bad gigahorse

I thinks that all replots farm to bladebit.

**Comment by sobertram** [comment]
Noticed recently sometimes the farm gets out of sync and will get stuck at a height without progressing.  I recently started using gh so not sure if this is already a known issue or something happening because of the dust storm.

Try restarting your farmer and see if starts synching again. This was the only way I am able to get mine working again.  

Can you share what version, `./chia.bin version`, of 2.1.1 you are running and also run `./chia.bin show -s` and `./chia.bin peer full_node -c`. and share the output?

I am on `2.1.1.giga25`.

You also should have the chia network version `2.1.1` installed and not `2.1.2` or `2.1.3`.

**Comment by LimakKAAM** [comment]
I have version chia app 2.1.1 and gigahorse 25. My system is windows server. Without problems before that.

**Comment by Kruger1981** [comment]
What do the logs say?

**Comment by LimakKAAM** [comment]
I instaled ubuntu and sytem working right now.
